spring:
  application:
    name: customer-service-onboard
  pidfile: ${APP_HOME}${spring.application.name}.pid

server:
  port: 8080

db:
  username: song
  password:
  instance: postgres
  url: jdbc:postgresql://localhost/dvdrental
  driver: org.postgresql.Driver